server:
  port: 9100 # 端口号递增
spring:
  application:
    name: lagou-service-page
  datasource:
    url: jdbc:mysql://localhost:3306/my?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver