server:
  port: 9000
spring:
  application:
    name: lagou-service-product
  datasource:
    url: jdbc:mysql://localhost:3306/my?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: abc123456
    driver-class-name: com.mysql.cj.jdbc.Driver